Vagrant.configure("2") do |config|
  config.vm.box = 'generic/ubuntu2004'
  config.vm.hostname = 'elk-stack'
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 8192
    libvirt.random_hostname = true
    libvirt.cpus = 2
  end
  config.vm.define :network do |network|
    network.vm.network :private_network, :ip => '172.168.0.2'
  end
end

