filebeat.inputs:
  - type: log
    paths:
      - /var/log/syslog
  - type: docker
    combine_partial: true
    containers:
      path: /var/lib/docker/containers
      stream: stdout
      ids:
        - '*'
output.logstash:
  hosts: ['127.0.0.1:5044']
