- name: install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip
    update_cache: yes

- name: install required python modules
  pip:
    name: docker
    state: present

- name: add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add deb repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable

- name: install Docker
  apt:
    name: docker-ce
    update_cache: yes

- name: add user {{ ansible_user }} to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
